CREATE TABLE BANK_ACCOUNT (
	OWNER CHAR(50),
	BALANCE DOUBLE,
	ACCOUNT_NUMBER INTEGER
);

create table product 
(
	product_code INTEGER,
	PRODUCT_NAME CHAR(100),
	PRICE DOUBLE,
	STOCK_COUNT INTEGER
);

INSERT INTO BANK_ACCOUNT (OWNER, BALANCE, ACCOUNT_NUMBER) VALUES ('Esma Meral',1000,345)

INSERT INTO PRODUCT (PRODUCT_CODE,PRODUCT_NAME,PRICE,STOCK_COUNT) VALUES (40,'All in One Printer',200,10);
